apiVersion: v1
kind: ResourceQuota
metadata:
  name: default-quota
  namespace: default
spec:
  hard:
    limits.cpu: '20'
    limits.memory: 80Gi
    pods: '75'
    requests.cpu: '10'
    requests.memory: 40Gi
