apiVersion: v1
kind: ResourceQuota
metadata:
  name: default-quota
  namespace: default
spec:
  hard:
    limits.cpu: '32'
    limits.memory: 128Gi
    pods: '100'
    requests.cpu: '16'
    requests.memory: 64Gi
